### ISSUE TITLE
Error with Google+

### ISSUE THREAD

**Issue by kwinkel** [samuelthomas2774/oauth-client#1]
Code:
http://i.gyazo.com/4aa6dad3e20841ee91c3af1ca5e3ed4e.png

Output: 
http://i.gyazo.com/4c5cd85629fe9bc455d5c2034b58d044.png

**Comment by samuelthomas2774** [comment]
Hi, I've been working on a [new version](/samuelthomas2774/oauth-client/tree/v1.0) and just released it, it should fix the warning messages here.

**Comment by kwinkel** [comment]
redirect to google and back to my page does work, but accessToken() is still null.
$curl_response in oauthrequest.class.php is empty when I use getAccessTokenByCode
